#!/bin/sh

NAME="uuidd"
DAEMON="/usr/sbin/uuidd"

start()
{
	printf "Starting ${NAME}: "
	mkdir -p "/run/uuidd"
	daemon -n ${NAME} -r -- "${DAEMON}" -P -F -q
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop()
{
	printf "Stopping ${NAME}: "
	if daemon --stop -n ${NAME}
	then
		echo "OK"
	else
		echo "FAIL"
	fi
}

running()
{
	exec daemon --running -n ${NAME}
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		start
		;;
	running)
		running
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}" >&2
		exit 1
		;;
esac
